Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,32 +62,17 @@ jobs:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: ${{ secrets.SSH_PORT || 22 }}
         script: |
-          echo "JAR file has been copied to ${{ secrets.TARGET_DIR }}"
+          echo "1"
+          cd ${{ secrets.TARGET_DIR }}/target
           
-          # Navigate to the target directory on the server
-          cd ${{ secrets.TARGET_DIR }}
-          
-          # Stop the existing application (adjust as needed)
-          #echo "Attempting to stop existing application..."
-          # Option 1: Using pkill (ensure APP_JAR_NAME is unique enough for this command)
-          #sudo pkill -f 'java -jar ${{ secrets.APP_JAR_NAME }}' || echo "No process found running with name ${{ secrets.APP_JAR_NAME }} or failed to kill."
-          # Option 2: If you know the port (e.g., 8080)
-          # PID=$(sudo lsof -t -i:8080)
-          # if [ -n "$PID" ]; then
-          #   echo "Stopping application on port 8080 with PID $PID"
-          #   sudo kill -9 $PID
-          # else
-          #   echo "No application found running on port 8080."
-          # fi
-          
-          # Give a moment for the port to be released if necessary
-          #sleep 5 
+          echo "2"
+          sudo pkill -f 'java -jar *.jar' || echo "No process found running with name ${{ secrets.APP_JAR_NAME }} or failed to kill."
+
+          echo "3"
+          sleep 5 
 
           # Start the new application
           # echo "Starting new application: ${{ secrets.APP_JAR_NAME }}"
           # Run in background, redirect output to app.log
           # Add any Java options or Spring profiles as needed.
           # nohup java -jar -Dserver.port=8080 ${{ secrets.APP_JAR_NAME }} --spring.profiles.active=prod > app.log 2>&1 &
-          
-          echo "Application deployment script executed. Check logs with: tail -f ${{ secrets.TARGET_DIR }}/app.log"
-          echo "To check if process is running: ps aux | grep '${{ secrets.APP_JAR_NAME }}'"
